/**
 * Error codes for the expense management system
 */
export const ErrorCodes = {
  // Authentication & Authorization
  AUTH_INVALID_CREDENTIALS: 'AUTH_001',
  AUTH_TOKEN_EXPIRED: 'AUTH_002',
  AUTH_TOKEN_INVALID: 'AUTH_003',
  AUTH_UNAUTHORIZED: 'AUTH_004',
  AUTH_FORBIDDEN: 'AUTH_005',
  AUTH_EMAIL_EXISTS: 'AUTH_006',
  AUTH_EMAIL_NOT_FOUND: 'AUTH_007',
  AUTH_PASSWORD_WEAK: 'AUTH_008',

  // User Management
  USER_NOT_FOUND: 'USER_001',
  USER_ALREADY_EXISTS: 'USER_002',
  USER_INACTIVE: 'USER_003',
  USER_SUSPENDED: 'USER_004',

  // Account Management
  ACCOUNT_NOT_FOUND: 'ACCOUNT_001',
  ACCOUNT_INSUFFICIENT_BALANCE: 'ACCOUNT_002',
  ACCOUNT_INVALID_TYPE: 'ACCOUNT_003',
  ACCOUNT_CURRENCY_MISMATCH: 'ACCOUNT_004',

  // Transaction Management
  TRANSACTION_NOT_FOUND: 'TRANSACTION_001',
  TRANSACTION_INVALID_AMOUNT: 'TRANSACTION_002',
  TRANSACTION_INVALID_DATE: 'TRANSACTION_003',
  TRANSACTION_CATEGORY_REQUIRED: 'TRANSACTION_004',

  // Category Management
  CATEGORY_NOT_FOUND: 'CATEGORY_001',
  CATEGORY_IN_USE: 'CATEGORY_002',
  CATEGORY_INVALID_TYPE: 'CATEGORY_003',

  // Budget Management
  BUDGET_NOT_FOUND: 'BUDGET_001',
  BUDGET_OVERLAP: 'BUDGET_002',
  BUDGET_INVALID_PERIOD: 'BUDGET_003',
  BUDGET_EXCEEDED: 'BUDGET_004',

  // Goal Management
  GOAL_NOT_FOUND: 'GOAL_001',
  GOAL_ALREADY_COMPLETED: 'GOAL_002',
  GOAL_INVALID_TARGET: 'GOAL_003',

  // Debt Management
  DEBT_NOT_FOUND: 'DEBT_001',
  DEBT_INVALID_AMOUNT: 'DEBT_002',
  DEBT_ALREADY_PAID: 'DEBT_003',

  // File Upload
  FILE_TOO_LARGE: 'FILE_001',
  FILE_INVALID_TYPE: 'FILE_002',
  FILE_UPLOAD_FAILED: 'FILE_003',

  // General
  VALIDATION_FAILED: 'VALIDATION_001',
  INTERNAL_SERVER_ERROR: 'SERVER_001',
  NOT_FOUND: 'NOT_FOUND_001',
  BAD_REQUEST: 'BAD_REQUEST_001',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_001',
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];