import { CategoryType } from '../../common/constants/enums';

export const defaultCategories = [
  // Income Categories
  {
    name: 'Lương',
    type: CategoryType.INCOME,
    icon: 'salary',
    color: '#4CAF50',
    isDefault: true,
    sortOrder: 1,
  },
  {
    name: 'Thưởng',
    type: CategoryType.INCOME,
    icon: 'bonus',
    color: '#8BC34A',
    isDefault: true,
    sortOrder: 2,
  },
  {
    name: 'Đầu tư',
    type: CategoryType.INCOME,
    icon: 'investment',
    color: '#CDDC39',
    isDefault: true,
    sortOrder: 3,
  },
  {
    name: 'Thu nhập phụ',
    type: CategoryType.INCOME,
    icon: 'side-income',
    color: '#FFC107',
    isDefault: true,
    sortOrder: 4,
  },

  // Expense Categories
  {
    name: 'Ăn uống',
    type: CategoryType.EXPENSE,
    icon: 'food',
    color: '#FF9800',
    isDefault: true,
    sortOrder: 1,
  },
  {
    name: 'Di chuyển',
    type: CategoryType.EXPENSE,
    icon: 'transport',
    color: '#FF5722',
    isDefault: true,
    sortOrder: 2,
  },
  {
    name: 'Mua sắm',
    type: CategoryType.EXPENSE,
    icon: 'shopping',
    color: '#E91E63',
    isDefault: true,
    sortOrder: 3,
  },
  {
    name: 'Giải trí',
    type: CategoryType.EXPENSE,
    icon: 'entertainment',
    color: '#9C27B0',
    isDefault: true,
    sortOrder: 4,
  },
  {
    name: 'Hóa đơn',
    type: CategoryType.EXPENSE,
    icon: 'bills',
    color: '#673AB7',
    isDefault: true,
    sortOrder: 5,
  },
  {
    name: 'Sức khỏe',
    type: CategoryType.EXPENSE,
    icon: 'health',
    color: '#3F51B5',
    isDefault: true,
    sortOrder: 6,
  },
  {
    name: 'Giáo dục',
    type: CategoryType.EXPENSE,
    icon: 'education',
    color: '#2196F3',
    isDefault: true,
    sortOrder: 7,
  },
  {
    name: 'Nhà cửa',
    type: CategoryType.EXPENSE,
    icon: 'housing',
    color: '#03DAC6',
    isDefault: true,
    sortOrder: 8,
  },
  {
    name: 'Khác',
    type: CategoryType.EXPENSE,
    icon: 'other',
    color: '#607D8B',
    isDefault: true,
    sortOrder: 9,
  },
];
